# Generated by Django 4.0.2 on 2022-02-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
